### ISSUE TITLE
Can't resolve rxjs/subject

### ISSUE THREAD

**Issue by ArmandoPerdomo** [bougarfaoui/ui-carousel#29]
Make posible run with rxjs 6+

**Comment by lchioukh** [comment]
+1

> Error: Can't resolve 'rxjs/add/operator/throttleTime' in '....\node_modules\ui-carousel\dist\src\ui-carousel'

> Error: Can't resolve 'rxjs/Subject' in '...\node_modules\ui-carousel\dist\src\ui-carousel'

**Comment by t-avil** [comment]
Did anyone get the answer ? coz i have the same problem

**Comment by sebastianfdez** [comment]
Solved in https://github.com/bougarfaoui/ui-carousel/pull/30

**Comment by ronaldohoch** [comment]
Hello!
I installed today and still continues with this error.
Is the solution in NPM?

**Comment by JohnnyBravo85** [comment]
For me too
